// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: wallets.sql

package db

import (
	"context"
	"database/sql"
)

const createGuestWallet = `-- name: CreateGuestWallet :one
INSERT INTO wallets (
        guests_id,
        wallets_type_id,
        token,
        balance
    )
VALUES ($1, $2, $3, $4)
RETURNING id, created_at, guests_id, wallets_type_id, token, balance
`

type CreateGuestWalletParams struct {
	GuestsID      int32         `json:"guests_id"`
	WalletsTypeID int32         `json:"wallets_type_id"`
	Token         string        `json:"token"`
	Balance       sql.NullInt32 `json:"balance"`
}

func (q *Queries) CreateGuestWallet(ctx context.Context, arg CreateGuestWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createGuestWallet,
		arg.GuestsID,
		arg.WalletsTypeID,
		arg.Token,
		arg.Balance,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GuestsID,
		&i.WalletsTypeID,
		&i.Token,
		&i.Balance,
	)
	return i, err
}

const deleteGuestWallet = `-- name: DeleteGuestWallet :exec
DELETE FROM wallets
WHERE id = $1
`

func (q *Queries) DeleteGuestWallet(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteGuestWallet, id)
	return err
}

const updateGuestWalletBalance = `-- name: UpdateGuestWalletBalance :one
UPDATE wallets
SET balance = $1
WHERE id = $2
RETURNING id, created_at, guests_id, wallets_type_id, token, balance
`

type UpdateGuestWalletBalanceParams struct {
	Balance sql.NullInt32 `json:"balance"`
	ID      int32         `json:"id"`
}

func (q *Queries) UpdateGuestWalletBalance(ctx context.Context, arg UpdateGuestWalletBalanceParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateGuestWalletBalance, arg.Balance, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GuestsID,
		&i.WalletsTypeID,
		&i.Token,
		&i.Balance,
	)
	return i, err
}

const updateGuestWalletToken = `-- name: UpdateGuestWalletToken :one
UPDATE wallets
SET token = $1
WHERE id = $2
RETURNING id, created_at, guests_id, wallets_type_id, token, balance
`

type UpdateGuestWalletTokenParams struct {
	Token string `json:"token"`
	ID    int32  `json:"id"`
}

func (q *Queries) UpdateGuestWalletToken(ctx context.Context, arg UpdateGuestWalletTokenParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateGuestWalletToken, arg.Token, arg.ID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.GuestsID,
		&i.WalletsTypeID,
		&i.Token,
		&i.Balance,
	)
	return i, err
}
