definitions:
  entities.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  handler.User:
    properties:
      email:
        type: string
      firstname:
        type: string
      lastname:
        type: string
      phone:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /users/{id}:
    get:
      description: get user with current sessions
      parameters:
      - description: Authentication token
        in: header
        name: auth
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/entities.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/entities.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/entities.HTTPError'
      summary: Get current urser data
      tags:
      - users
swagger: "2.0"
